import time
import logging
import base64
import cv2
from typing import Dict, Any, Union, Optional
from pathlib import Path
import numpy as np
import tensorflow as tf

from ml.datasets.dicom_nifti import read_image_as_rgb
from ml.preprocessing.normalization import preprocess_image_array
from ml.models.registry import ModelRegistry
from ml.explainability.gradcam import GradCAMGenerator

logger = logging.getLogger(__name__)

MEDICAL_DISCLAIMER: str = (
    "DISCLAIMER: This prediction is generated by an AI research decision-support model "
    "and is NOT a certified medical diagnostic result. It is intended solely for educational, "
    "research, and clinical decision-support purposes. Consult a licensed neurologist or "
    "medical specialist for clinical diagnosis."
)

DEFAULT_CLASSES = ["Non Demented", "Very Mild Demented", "Mild Demented", "Moderate Demented"]


class MRIPredictor:
    """
    Inference orchestrator that handles MRI file/bytes reading, preprocessing,
    model forward pass, prediction confidence formatting, Grad-CAM heatmap generation,
    and medical disclaimer embedding.
    """

    def __init__(
        self,
        model_name: str = "custom_cnn",
        weights_path: Optional[Union[str, Path]] = None,
        class_names: Optional[list] = None
    ):
        self.model_name = model_name
        self.class_names = class_names or DEFAULT_CLASSES
        self.weights_path = Path(weights_path) if weights_path else None
        self.model_wrapper = None
        self.gradcam = None

        self._initialize_model()

    def _initialize_model(self):
        """Instantiates and loads model architecture and weights."""
        logger.info(f"Initializing predictor with model architecture: {self.model_name}")
        self.model_wrapper = ModelRegistry.create_model(
            model_name=self.model_name,
            input_shape=(224, 224, 3),
            num_classes=len(self.class_names)
        )

        if self.weights_path and self.weights_path.exists():
            logger.info(f"Loading trained model weights from {self.weights_path}")
            self.model_wrapper.load(str(self.weights_path))

        target_layer = self.model_wrapper.get_gradcam_target_layer_name()
        self.gradcam = GradCAMGenerator(self.model_wrapper.model, target_layer_name=target_layer)

    def predict(
        self,
        image_input: Union[str, Path, bytes],
        generate_gradcam: bool = True
    ) -> Dict[str, Any]:
        """
        Executes end-to-end inference on input MRI image.
        
        Returns dictionary with keys:
        - predicted_class: str
        - confidence: float
        - class_probabilities: Dict[str, float]
        - inference_time_ms: float
        - original_base64: str
        - heatmap_base64: str (optional)
        - overlay_base64: str (optional)
        - medical_disclaimer: str
        """
        start_time = time.time()

        # 1. Read & Preprocess Image
        rgb_raw = read_image_as_rgb(image_input, target_size=(224, 224))
        norm_img = preprocess_image_array(rgb_raw, target_size=(224, 224), normalize_pixels=True)
        input_batch = np.expand_dims(norm_img, axis=0)

        # Convert rgb_raw to Base64 PNG URL for reliable frontend rendering
        _, buffer = cv2.imencode(".png", cv2.cvtColor(rgb_raw, cv2.COLOR_RGB2BGR))
        original_b64 = f"data:image/png;base64,{base64.b64encode(buffer).decode('utf-8')}"

        # 2. Forward Pass
        probs = self.model_wrapper.model.predict(input_batch, verbose=0)[0]
        top_idx = int(np.argmax(probs))
        predicted_class = self.class_names[top_idx]
        confidence = float(probs[top_idx])

        probs_dict = {
            self.class_names[i]: float(probs[i])
            for i in range(len(self.class_names))
        }

        # 3. Grad-CAM visual explanation
        heatmap_b64, overlay_b64 = None, None
        if generate_gradcam and self.gradcam:
            try:
                cam_res = self.gradcam.generate_gradcam_response(rgb_raw, pred_index=top_idx)
                heatmap_b64 = cam_res["heatmap_base64"]
                overlay_b64 = cam_res["overlay_base64"]
            except Exception as e:
                logger.error(f"Grad-CAM generation error: {e}")

        inference_time = round((time.time() - start_time) * 1000.0, 2)

        return {
            "predicted_class": predicted_class,
            "confidence": round(confidence, 4),
            "class_probabilities": probs_dict,
            "inference_time_ms": inference_time,
            "model_version": self.model_name,
            "original_base64": original_b64,
            "heatmap_base64": heatmap_b64,
            "overlay_base64": overlay_b64,
            "medical_disclaimer": MEDICAL_DISCLAIMER
        }
